# Make sure the EventCatalog MCP server can build and test OK
name: Verify Build and Test

on:
  pull_request:
    branches:
      - master
      - main

permissions:
  contents: read

jobs:
  build:
    name: Verify Build and Test
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2
        with:
          use-policy-store: true
          api-key: ${{ secrets.GH_FRESHAENGINEERING_STEP_SECURITY_API_KEY }}

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
      - name: Setup mise
        uses: step-security/mise-action@6e96d2ffbc65c037f23c78818f2a339d6cf830f7 # v4.2.4
        with:
          version: '2026.8.12'
      - name: Setup pnpm
        uses: step-security/action-setup@c9d80a280aaf584da8c913342a763a6de6452c7a # v5.0.0
        with:
          version: 8
      - name: Installation
        run: pnpm i
      - name: Test
        run: pnpm run test
      - name: Build package
        run: pnpm run build